name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Clean CMake cache
      run: rm -rf _build

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON -DCOVERAGE=ON

    - name: Build
      run: cmake --build _build

    - name: Run tests
      run: ctest --output-on-failure --test-dir _build

    - name: Check for coverage files
      run: find _build -name '*.gcda'

    - name: Capture coverage info
      run: lcov --capture --directory _build --output-file coverage.info

    - name: Show coverage summary
      run: lcov --list coverage.info
