name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON -DCOVERAGE=ON

    - name: Build
      run: cmake --build _build

    - name: Run tests
      run: ctest --test-dir _build --output-on-failure

    - name: Collect coverage
      run: |
        lcov --capture --directory _build --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/third-party/*' --output-file coverage.info
        lcov --list coverage.info
