name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive   # вот тут подтянем gtest правильно

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Configure and build
      run: |
        rm -rf _build
        mkdir _build
        cd _build
        cmake .. -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="--coverage"
        cmake --build .

    - name: Run tests
      run: ./_build/my_test

    - name: Capture coverage info
      run: |
        mkdir -p coverage
        lcov --capture --directory _build --output-file coverage/lcov.info --rc lcov_branch_coverage=1

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage/lcov.info
