name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential lcov

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON

    - name: Build project
      run: cmake --build _build

    - name: Run tests
      run: ctest --test-dir _build --output-on-failure

    - name: Capture coverage
      run: lcov --capture --directory _build --output-file coverage.info --rc geninfo_ignore_errors=mismatch,gcov,empty,source --rc geninfo_unexecuted_blocks=1

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.info
