name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Clean build directory
      run: rm -rf _build

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON -DCOVERAGE=ON

    - name: Build
      run: cmake --build _build

    - name: Run tests
      run: cmake --build _build --target test

    - name: Collect coverage
      run: lcov --capture --directory _build --output-file coverage.info --rc geninfo_ignore_errors=mismatch
