name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov cmake g++ gcc

    - name: Set up googletest
      run: |
        git clone https://github.com/google/googletest.git third-party/googletest
        mkdir -p third-party/googletest/build
        cd third-party/googletest/build
        cmake ..
        make

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON -DCOVERAGE=ON

    - name: Build
      run: cmake --build _build

    - name: Run tests
      run: cd _build && ctest

    - name: Collect coverage
      run: |
        lcov --directory _build --capture --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/googletest/*' --output-file coverage.info
        lcov --list coverage.info
