name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov

    - name: Clean build directory
      run: rm -rf _build

    - name: Configure CMake
      run: cmake -S . -B _build -DBUILD_TESTS=ON -DCOVERAGE=ON

    - name: Build project
      run: cmake --build _build -- -j$(nproc)

    - name: Run tests
      run: ctest --output-on-failure --test-dir _build

    - name: Capture coverage info
      run: lcov --capture --directory _build --output-file coverage.info

    - name: Show coverage summary
      run: lcov --list coverage.info
