jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clone googletest
        run: git clone --depth=1 https://github.com/google/googletest.git third-party/googletest

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y lcov

      - name: Clean build directory
        run: rm -rf _build

      - name: Configure CMake
        run: cmake -S . -B _build -DBUILD_TESTS=ON -DCOVERAGE=ON

      - name: Build project
        run: cmake --build _build -- -j$(nproc)

      - name: Run tests
        run: ctest --output-on-failure --test-dir _build

      - name: Capture coverage info
        run: lcov --capture --directory _build --output-file coverage.info

      - name: Show coverage summary
        run: lcov --list coverage.info
